# This file was generated by FitSNAP.
# Hash: 05700139dce9e7e22dbb3fabbfa3c600

pair_style hybrid/overlay zbl 4.0 4.8 snap
pair_coeff * * zbl 73 73
pair_coeff * * snap Ta_pot.snapcoeff Ta_pot.snapparam Ta