# This file was generated by FitSNAP.
# Hash: 0a5a28d7c84c42c35282e73eef13f953

pair_style hybrid/overlay zbl 4.0 4.8 snap
pair_coeff * * zbl 73 73
pair_coeff * * snap Ta_pot.snapcoeff Ta_pot.snapparam Ta