# This file was generated by FitSNAP.
# Hash: 4b3086c5dd398a05da56ee22f0fb807e

pair_style hybrid/overlay zbl 4.0 4.8 snap
pair_coeff * * zbl 73 73
pair_coeff * * snap Ta_pot.snapcoeff Ta_pot.snapparam Ta