# This file was generated by FitSNAP.
# Hash: 73e87f99ca5ee3e2efb4f351e0a5cb0b

pair_style hybrid/overlay zbl 4.0 4.8 snap
pair_coeff * * zbl 73 73
pair_coeff * * snap Ta_pot.snapcoeff Ta_pot.snapparam Ta