# This file was generated by FitSNAP.
# Hash: c5db72230c4825a3b9e95892a4e5658e

pair_style hybrid/overlay zbl 4.0 4.8 snap
pair_coeff * * zbl 73 73
pair_coeff * * snap Ta_pot.snapcoeff Ta_pot.snapparam Ta