# This file was generated by FitSNAP.
# Hash: 071656b25bf8b4ee9514041dfeba4829

pair_style hybrid/overlay zbl 4.0 4.8 snap
pair_coeff * * zbl 73 73
pair_coeff * * snap Ta_pot.snapcoeff Ta_pot.snapparam Ta