# This file was generated by FitSNAP.
# Hash: cfd644f0d07fe2f0ce6d12a967d64b48

pair_style hybrid/overlay zbl 4.0 4.8 snap
pair_coeff * * zbl 73 73
pair_coeff * * snap Ta_pot.snapcoeff Ta_pot.snapparam Ta