# This file was generated by FitSNAP.
# Hash: 6a46316a396b5e7cc82930b1519fc70a

pair_style hybrid/overlay zbl 4.0 4.8 snap
pair_coeff * * zbl 73 73
pair_coeff * * snap Ta_pot.snapcoeff Ta_pot.snapparam Ta