# This file was generated by FitSNAP.
# Hash: 61eb2460fc2e8f5eefe2e441e30327e9

pair_style hybrid/overlay zbl 4.0 4.8 snap
pair_coeff * * zbl 73 73
pair_coeff * * snap Ta_pot.snapcoeff Ta_pot.snapparam Ta