# This file was generated by FitSNAP.
# Hash: 02e0de554ad6e0e5c8ebba0149d9f235

pair_style hybrid/overlay zbl 4.0 4.8 snap
pair_coeff * * zbl 73 73
pair_coeff * * snap Ta_pot.snapcoeff Ta_pot.snapparam Ta