# This file was generated by FitSNAP.
# Hash: 7222a418f751300c107a479b4762e370

pair_style hybrid/overlay zbl 4.0 4.8 snap
pair_coeff * * zbl 73 73
pair_coeff * * snap Ta_pot.snapcoeff Ta_pot.snapparam Ta