# This file was generated by FitSNAP.
# Hash: acb5cd7cc62607de19d53471945bf2f7

pair_style hybrid/overlay zbl 4.0 4.8 snap
pair_coeff * * zbl 73 73
pair_coeff * * snap Ta_pot.snapcoeff Ta_pot.snapparam Ta