# This file was generated by FitSNAP.
# Hash: 732abfd68a931dbb1e9559a5f034c7a3

pair_style hybrid/overlay zbl 4.0 4.8 snap
pair_coeff * * zbl 73 73
pair_coeff * * snap Ta_pot.snapcoeff Ta_pot.snapparam Ta