# This file was generated by FitSNAP.
# Hash: b85d424ccef894c2b275d3fa69343b0c

pair_style hybrid/overlay zbl 4.0 4.8 snap
pair_coeff * * zbl 73 73
pair_coeff * * snap Ta_pot.snapcoeff Ta_pot.snapparam Ta