# This file was generated by FitSNAP.
# Hash: 9676afa78fb228d7f14721d1c172f61c

pair_style hybrid/overlay zbl 4.0 4.8 snap
pair_coeff * * zbl 73 73
pair_coeff * * snap Ta_pot.snapcoeff Ta_pot.snapparam Ta