# This file was generated by FitSNAP.
# Hash: 9d4ae5f99d8d9400fe3c9a06da230eb7

pair_style hybrid/overlay zbl 4.0 4.8 snap
pair_coeff * * zbl 73 73
pair_coeff * * snap Ta_pot.snapcoeff Ta_pot.snapparam Ta