# This file was generated by FitSNAP.
# Hash: 6183597f09330658974d667b1ac15692

pair_style hybrid/overlay zbl 4.0 4.8 snap
pair_coeff * * zbl 73 73
pair_coeff * * snap Ta_pot.snapcoeff Ta_pot.snapparam Ta