# This file was generated by FitSNAP.
# Hash: 13d9bff132c6d50f219e350bf8ac4a4c

pair_style hybrid/overlay zbl 4.0 4.8 snap
pair_coeff * * zbl 73 73
pair_coeff * * snap Ta_pot.snapcoeff Ta_pot.snapparam Ta