# This file was generated by FitSNAP.
# Hash: 5d7db95dbaea23daa614f650f60a3db5

pair_style hybrid/overlay zbl 4.0 4.8 snap
pair_coeff * * zbl 73 73
pair_coeff * * snap Ta_pot.snapcoeff Ta_pot.snapparam Ta